---
title: "Lifetime Inequality: Cross-sectional"
output: html_notebook
---

```{r Setup}
# Dont need code to show
knitr::opts_chunk$set(echo = F)
# Packages
pacman::p_load(
  tidyverse,
  here,
  arrow,
  janitor
)

# Folders
data_raw <- "G:/aLifeData/ALife2019a/csv" # Original raw data
data_dir <- "P:/IND2019a2021007/Nabeeh/Raw_data" # Extracted raw data
data_proc <- here("Lifetime_inequality","Processed_data") 

# CPI
CPI <- 
  read_csv(here(data_dir,"CPI.csv"),show_col_types = F)
```

# Introduction

This file contains summary statistics.

Sample restrictions:

1.  Remove those below 20 years

2.  Remove those with negative labour, capital, public incomes and tax.

# Frequencies and summary statistics

```{r f_exclude}
f_exclude <- 
  function(A){
    A %>% 
      mutate(
        insample="sample",
        insample=
          if_else(
            inc_lab<0|inc_cap<0|inc_pub<0|inc_tax<0|inc_pre<0|inc_post_pub<0|
              inc_net<0,
            "excluded",
            insample
          ),
        insample=
          if_else(
            age<20|is.na(age),"excluded",insample
          )
      )
  }

f_temp <- 
  function(A){
    A %>% 
    filter(!is.na(x)) %>% summarise(mean=mean(x),sd=sd(x),median=median(x))
  }

f_temp2 <- 
  function(A){
X <- 
  bind_rows(
    A %>%  rename(x=age) %>% f_temp(.) %>%  
      collect() %>% mutate(var="age") ,
    A %>%  rename(x=inc_lab) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_lab") ,
    A %>%  rename(x=inc_cap) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_cap") ,
    A %>%  rename(x=inc_pub) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_pub") ,
    A %>%  rename(x=inc_tax) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_tax") ,
    A %>%  rename(x=inc_pre) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_pre") ,
    A %>%  rename(x=inc_post_pub) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_post_pub") ,
    A %>%  rename(x=inc_net) %>% f_temp(.) %>%  
      collect() %>% mutate(var="inc_net") ,
    A %>%  rename(x=ic_taxable_income_loss) %>% f_temp(.) %>%  
      collect() %>% mutate(var="ic_taxable_income_loss") ,
    A %>%  rename(x=ic_total_income_loss) %>% f_temp(.) %>%  
      collect() %>% mutate(var="ic_total_income_loss") 
  ) %>% 
  relocate(var)
}
```

```{r}
v_year <- c(1991:2019)
for (i in seq_along(v_year)) {
yr = v_year[i]
A <- 
  read_feather(paste0(data_dir, "/LI_01_Derived_", yr, ".feather"),
               as_data_frame = F) %>% 
  select(-ends_with("_2")) %>% 
  rename_with(.,~str_remove(.,"_1")) %>% 
  mutate(inc_pre=inc_lab+inc_cap,
         inc_post_pub=inc_pre+inc_pub,
         inc_net=inc_post_pub-inc_tax) %>% 
  f_exclude() %>% 
  collect() %>% 
  left_join(.,CPI,by="year") %>% 
  mutate(
    across(
       c(starts_with("inc_"),starts_with("ic_"),starts_with("isc_")),
      ~./cpi
    )
  ) 

# FREQUENCIES
Z <- 
  bind_rows(
    # Full dataset
    ## Both sexes
    A %>% summarise(n=n()) %>%  
      mutate(insample="data",sex="Both"),
    ## By sex
    A %>% group_by(sex) %>% summarise(n=n()) %>%  
      mutate(insample="data"),
    # By insample
    A %>% group_by(insample) %>% summarise(n=n()) %>%  
      mutate(sex="Both"),
    ## Both sexes
    A %>% group_by(insample,sex) %>% summarise(n=n()) 
  ) %>% 
  mutate(year=yr) %>% 
  pivot_wider(names_from = sex, values_from = n) %>% 
  relocate(year)

if (i==1){
  Freq_sex=Z
}
else{
  Freq_sex=bind_rows(Freq_sex,Z)
}

# SUMMARY STATS
Z <- 
  bind_rows(
    A %>% f_temp2() %>%   mutate(insample="data",sex="Both"),
    A %>% group_by(sex) %>% f_temp2() %>%   mutate(insample="data"),
    A %>% group_by(insample) %>% f_temp2() %>%   mutate(sex="Both"),
    A %>% group_by(insample,sex) %>% f_temp2()
  ) %>% 
  mutate(year=yr) %>% 
  relocate(year,var,insample,sex)

if (i==1){
  Sum_stats=Z
}
else{
  Sum_stats=bind_rows(Sum_stats,Z)
}
print(v_year[i])
}
```

```{r}
write_csv(Freq_sex,
          here(data_proc,
               "LI_02_Frequencies_data_sample_excluded_by_sex.csv"))

write_csv(Sum_stats,
          here(data_proc,
               "LI_02_Summary_stats_data_sample_excluded_by_sex.csv"))
```

# By quantiles

### Means

```{r}
f_quant <- 
  function(A,qq){
    A %>% 
      mutate(qx=ntile(inc_pre,qq)) %>% 
      group_by(qx,.add=T) %>% 
      summarise(
        across(
          starts_with("inc_"),
          mean
        )
      ) %>% 
      mutate(year=yr,quant=qq)    
  }
```

```{r}
v_year <- c(1991:2019)
for (i in seq_along(v_year)) {
yr = v_year[i]
A <- 
  read_feather(paste0(data_dir, "/LI_01_Derived_", yr, ".feather"),
               as_data_frame = F) %>% 
  select(-ends_with("_2")) %>% 
  rename_with(.,~str_remove(.,"_1")) %>% 
  mutate(inc_pre=inc_lab+inc_cap,
         inc_post_pub=inc_pre+inc_pub,
         inc_net=inc_post_pub-inc_tax) %>% 
  f_exclude() %>% 
  filter(insample=="sample") %>% 
  ungroup() %>% 
  collect() %>% 
  left_join(.,CPI,by="year") %>% 
  mutate(
    across(
      c(starts_with("inc_")),
      ~./cpi
    )
  ) 
   
Z <- 
  bind_rows(
    A %>% f_quant(.,5) ,
    A %>% f_quant(.,10) ,
    A %>% f_quant(.,100) ,
    A %>% f_quant(.,1000) %>% filter(qx==1000),
    
    A %>% filter(sex=="M") %>% f_quant(.,5) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,10) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,100) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,1000) %>% filter(qx==1000)  %>% 
      mutate(sex="M"),
    
    A %>% filter(sex=="F") %>% f_quant(.,5) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,10) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,100) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,1000) %>% filter(qx==1000)  %>% 
      mutate(sex="F"),
  ) %>% 
  rename(q=qx) %>% 
  relocate(year,sex,quant,q)

if(i==1){
  Q=Z
}
if(i>1){
  Q=bind_rows(Q,Z)
}
print(yr)  
}
```

```{r}
write_csv(Q,
          here(data_proc,
               "LI_02_Cross_quantile_means_all_and_by_sex.csv"))
```

### Shares

```{r f_shares}
f_quant <- 
  function(A,qq){
    A %>% 
      arrange(inc_pre) %>% 
      mutate(qx=ntile(inc_pre,qq)) %>% 
      group_by(qx,.add=T) %>% 
      summarise(
        across(
          starts_with("inc_"),
          sum
        )
      ) %>% 
      ungroup() %>% 
      mutate(
        across(
          starts_with("inc_"),
          ~(./sum(.))*100
        )
      ) %>% 
      mutate(
        across(
          starts_with("inc_"),
          ~cumsum(.),
          .names = "{.col}_cumsum"
        )
      ) %>% 
      mutate(year=yr,quant=qq)    
  }
```

```{r}
v_year <- c(1991:2019)
for (i in seq_along(v_year)) {
yr = v_year[i]
A <- 
  read_feather(paste0(data_dir, "/LI_01_Derived_", yr, ".feather"),
               as_data_frame = F) %>% 
  select(-ends_with("_2")) %>% 
  rename_with(.,~str_remove(.,"_1")) %>% 
  mutate(inc_pre=inc_lab+inc_cap,
         inc_post_pub=inc_pre+inc_pub,
         inc_net=inc_post_pub-inc_tax) %>% 
  f_exclude() %>% 
  filter(insample=="sample") %>% 
  ungroup() %>% 
  collect()
   
Z <- 
  bind_rows(
    A %>% f_quant(.,5) ,
    A %>% f_quant(.,10) ,
    A %>% f_quant(.,100) ,
    A %>% f_quant(.,1000) %>% filter(qx==1000),
    
    A %>% filter(sex=="M") %>% f_quant(.,5) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,10) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,100) %>% mutate(sex="M"),
    A %>% filter(sex=="M") %>% f_quant(.,1000) %>% filter(qx==1000)  %>% 
      mutate(sex="M"),
    
    A %>% filter(sex=="F") %>% f_quant(.,5) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,10) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,100) %>% mutate(sex="F"),
    A %>% filter(sex=="F") %>% f_quant(.,1000) %>% filter(qx==1000)  %>% 
      mutate(sex="F"),
  ) %>% 
  rename(q=qx) %>% 
  relocate(year,sex,quant,q)

if(i==1){
  Q=Z
}
if(i>1){
  Q=bind_rows(Q,Z)
}
print(yr)  
}
```

```{r}
write_csv(Q,
          here(data_proc,
               "LI_02_Cross_quantile_shares_all_and_by_sex.csv"))
```

# Indices

```{r Indices}
# Calculate indices
f_indices <- 
  function(X){
    # Function to calculate area under curve
    f_area <- 
      function(x,y){
        h = x-lag(x)
        h = ifelse(is.na(h),0,h)
        ab = y+lag(y)
        ab = ifelse(is.na(ab),y,ab)
        L = sum(0.5*h*ab)
        K = 0.5
        S = 1-(L/K)
      }
    
    # Function to caclculate indices
    I <- 
      X %>% 
      # Restrict sample
      filter(x>=0&y>=0&t>=0) %>% 
      select(year,x,y,t) %>% 
      # Sample stats
      mutate(
        across(
          c('x','y','t'),
          list(Mean = mean, Tot = sum),
          .names = "{.fn}_{.col}"
        )
      ) %>% 
      # Average size
      mutate(
       size = Tot_t/Tot_x
      ) %>% 
      # Shares
      mutate(
        px = x/Tot_x, py = y/Tot_y, pt = t/Tot_t, num=1,
        obs =1/sum(num)
      ) %>% 
      # Distribution wrt x (Prefix 'X_')
      arrange(x) %>% 
      mutate(
        across(
          c('px','py','pt','obs'),
          cumsum,
          .names = "X_{.col}"
        ),
        
        # Indices (covariance formula)
        Gx_cov = (2/Mean_x)*(cov(x,X_obs)), # Gini coef
        Ct = (2/Mean_t)*(cov(t,X_obs)),
        St = (2/Mean_t)*(cov(t,X_px)),
        Cy_cov = (2/Mean_y)*(cov(y,X_obs)),
        K_cov  = Ct - Gx_cov,
        S_cov  = St - Gx_cov,
        
        # Indices (area formula)
        Gx_area = f_area(X_obs,X_px), 
        Cy_area = f_area(X_obs,X_py), 
        Ct = f_area(X_obs,X_pt),
        S_area = f_area(X_px,X_pt),
        K_area = Ct - Gx_area
      ) %>% 
      # Redistributive effect
      arrange(y) %>% 
      mutate(
        across(
          c('px','py','pt','obs'),
          cumsum,
          .names = "Y_{.col}"
        ),
        Gy_area = f_area(Y_obs,Y_py),
        Gy_cov  = (2/Mean_y)*(cov(y,Y_obs)),
        R_area = Gx_area - Cy_area,
        R_cov = Gx_cov - Cy_cov,
        Rerank_area = Gy_area - Cy_area,
        Rerank_cov = Gy_cov - Cy_cov,
      ) %>% 
      # Totals
      mutate(
        Tot_x=sum(x),Tot_y=sum(y),Tot_t=sum(t)
      ) %>% 
      select(year,ends_with('area')|ends_with('cov')|starts_with("Tot_")) %>% 
      filter(row_number()==1)
    
  }
```

```{r}
v_year <- c(1991:2019)
for (i in seq_along(v_year)) {
yr = v_year[i]
A <- 
  read_feather(paste0(data_dir, "/LI_01_Derived_", yr, ".feather"),
               as_data_frame = F) %>% 
  select(-ends_with("_2")) %>% 
  rename_with(.,~str_remove(.,"_1")) %>% 
  mutate(inc_pre=inc_lab+inc_cap,
         inc_post_pub=inc_pre+inc_pub,
         inc_net=inc_post_pub-inc_tax) %>% 
  f_exclude() %>% 
  filter(insample=="sample") %>% 
  ungroup() %>% 
  collect()
   
Z <- 
  bind_rows(
    A %>% 
      mutate(x=inc_pre,t=inc_tax,y=x-t) %>% 
      f_indices() %>% 
      mutate(xvar="inc_pre",tvar="inc_tax"),
    A %>% 
      mutate(x=inc_pre,t=inc_pub,y=x+t) %>% 
      f_indices() %>% 
      mutate(xvar="inc_pre",tvar="inc_pub"),
    A %>% 
      mutate(x=inc_pre,t=inc_pen,y=x+t) %>% 
      f_indices() %>% 
      mutate(xvar="inc_pre",tvar="inc_pen"),
    A %>% 
      mutate(x=inc_pre,t=inc_pub_other,y=x+t) %>% 
      f_indices() %>% 
      mutate(xvar="inc_pre",tvar="inc_pub_other"),
    A %>% 
      mutate(x=inc_pre,y=inc_net,t=x-y) %>% 
      f_indices() %>% 
      mutate(xvar="inc_pre",tvar="overall"),
    A %>% 
      mutate(x=inc_lab,y=inc_lab,t=x-y) %>% 
      f_indices() %>% 
      mutate(xvar="inc_lab",tvar="Only Gini x"),
    A %>% 
      mutate(x=inc_cap,y=inc_cap,t=x-y) %>% 
      f_indices() %>% 
      mutate(xvar="inc_cap",tvar="Only Gini x"),
    A %>% 
      mutate(x=inc_mixed,y=inc_mixed,t=x-y) %>% 
      f_indices() %>% 
      mutate(xvar="inc_mixed",tvar="Only Gini x"),
     A %>% 
      mutate(x=ic_taxable_income_loss,t=inc_tax,y=x-t) %>% 
      f_indices() %>% 
      mutate(xvar="ic_taxable_income_loss",tvar="inc_tax"),
    A %>% 
      mutate(x=ic_total_income_loss,t=inc_tax,y=x-t) %>% 
      f_indices() %>% 
      mutate(xvar="ic_total_income_loss",tvar="inc_tax")
  ) %>% 
  relocate(year,xvar,tvar)

if(i==1){
  Q=Z
}
if(i>1){
  Q=bind_rows(Q,Z)
}
print(yr)  
}
```

```{r}
write_csv(Q,
          here(data_proc,
               "LI_02_Cross_Indices.csv"))
```
